In [3]:
# Python program explaining
# hstack() function

import numpy as np

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [2]:
# Python program explaining
# hstack() function

import numpy as np

# input array
in_arr1 = np.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [[1 2 3]
 [4 5 6]]
