In [3]:
import numpy as np

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [28]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,100,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [ ]:
def zeros jnih
rdytfuf
gfxdyfyf
gdhffh

In [ ]:
def ones dfuhgiuhg
sdygfydghrbf
dsyfgyfvy

In [ ]:
def arange ghtydef ones dfuhgiuhg
sdygfydghrbf
dsyfgyfvy
rtujy
rtutyu

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
zeros((3,3))

NameError: name 'fdygurehfbgurgbfu' is not defined

In [25]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(())

In [ ]:
import numpy as np

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [18]:
np.random.rand(4,4)

array([[0.50244152, 0.94993415, 0.30703402, 0.6084145 ],
       [0.44151014, 0.93343804, 0.67018452, 0.54474063],
       [0.41590664, 0.19157386, 0.69596277, 0.51377459],
       [0.2912195 , 0.46174095, 0.99164357, 0.73441469]])

In [20]:
np.random.rand(4,5)# 
# [0---> 1]

array([[0.1900755 , 0.68851409, 0.06742371, 0.73726767, 0.69449283],
       [0.91213359, 0.87793066, 0.12733381, 0.84188124, 0.17687172],
       [0.82891642, 0.76451447, 0.96434132, 0.87678883, 0.8086376 ],
       [0.76142853, 0.51995702, 0.46171042, 0.56592225, 0.18379028]])

In [34]:
np.random.randint(0,100,10)

# [n --> k] int

array([97, 38, 67, 74, 36, 94, 35, 24, 68, 23])

In [43]:
ana_array =np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
omar = np.random.randint(0,100,10)

In [73]:
omar

array([28, 77,  9, 23, 54, 75, 35, 30, 60, 39])

In [50]:
ana_array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
raa

array([26, 71, 73, 70, 93, 30, 80,  0, 99,  9])

In [74]:
omar.max()

77

In [75]:
omar.min()

9

In [77]:
omar.argmax() # index

1

In [76]:
omar.argmin()

2

In [96]:
ana_array =np.arange(16)

In [99]:
ana_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [108]:
ana_array.shape

(16,)

In [110]:
c= ana_array.reshape(16,1)

In [111]:
c.shape

(16, 1)

In [145]:
att = np.arange(0,20)

In [141]:
att

2

In [139]:
lf = np.random.randint(0,20)

In [146]:
atrr = np.arange(0,20)
atrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [140]:
att+ lf

7

In [148]:
att*atrr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [113]:
att

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
att

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
att / att

C:\Users\AMIT\AppData\Local\Temp/ipykernel_6616/1100563834.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / att


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [134]:
liu = [1,2,3,4,5,5,8,9,6,5]

In [135]:
ff = [2,6,89,0]

In [136]:
liu + ff

[1, 2, 3, 4, 5, 5, 8, 9, 6, 5, 2, 6, 89, 0]

In [124]:
liu

[1, 2, 3, 4, 5, 5, 8, 9, 6, 5]

In [ ]:
e^0
e^1
e^2



In [149]:
np.exp(att)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [154]:
np.max(att)

19

In [157]:
att = np.arange(0,20)

In [160]:
att

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [158]:
att.max()

19

In [161]:
np.exp(att)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [150]:
2*2

4

In [151]:
2**2

4

In [152]:
2*3

6

In [153]:
2**3

8

In [162]:
np.sin(att)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [163]:
np.log(att)

C:\Users\AMIT\AppData\Local\Temp/ipykernel_6616/784945421.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(att)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [164]:
import pandas as pd