# NumPy 




In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
x=np.array(my_matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x.shape

(3, 3)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### zeros and ones

Generate arrays of zeros or ones

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [51]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [17]:
np.random.rand(4)

array([0.31726148, 0.41547392, 0.96857492, 0.50753009])

In [18]:
np.random.rand(5,5)

array([[0.79696507, 0.55073957, 0.91545058, 0.53675719, 0.29390599],
       [0.40924849, 0.63960001, 0.90363697, 0.15352438, 0.75435902],
       [0.4200849 , 0.28022998, 0.75842823, 0.8953792 , 0.94451809],
       [0.36448109, 0.47009793, 0.64847155, 0.08750038, 0.90853432],
       [0.59282464, 0.072506  , 0.78214703, 0.38538419, 0.70883065]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [19]:
np.random.randn(4)

array([ 0.2408297 ,  1.92871617, -1.23848453,  0.39562061])

In [56]:
np.random.randn(5,5)

array([[-1.44860596,  0.12170668, -0.35183035, -0.61668775, -0.48300764],
       [-0.52689655,  1.22294396, -0.01387469,  0.02790581,  0.38477372],
       [ 1.23666621,  1.18196576, -0.79581488, -0.12629743,  0.27286618],
       [ 0.53388774, -0.01477867,  0.78471061, -0.4597943 ,  0.94302005],
       [-1.01930363, -0.26083058,  0.20014768,  1.3312379 , -0.57095374]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [53]:
np.random.randint(1,40)

12

In [21]:
np.random.randint(1,100,10)

array([39, 54, 57, 56, 75, 26,  9, 49, 68, 98])

## Array Attributes and Methods


In [23]:
arr = np.arange(25)
ranarr= np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([28, 39, 39, 19, 26, 23, 25, 48, 28, 28])

## Reshape
Returns an array containing the same data with a new shape.

In [57]:
arr.reshape(x,y).shape

(5, 5)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([28, 39, 39, 19, 26, 23, 25, 48, 28, 28])

In [29]:
ranarr.max()

48

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.min()

19

In [32]:
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)