# 01 NumPy

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually
numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions
are called axes

In [ ]:
import numpy as np #  aliase name   array 4x2 

## 1. Array Creation
* np.array()
* np.zeros()
* np.ones()
* np.empty()
* np.eye()
* np.asarray()
* numpy.arange()
* np.linspace()
### 1.1 np.array()
Create an array.

* np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

In [ ]:
a = np.array([1,2,3,4,5,6]) # create a one-dimensional array
print("one-dimensional array:", a)

one-dimensional array: [1 2 3 4 5 6]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # create a multidimensional array  [[row1],[row2],[row3]]
print("multidimensional array:",'\n' ,b) #3x3 

multidimensional array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([(1,2,3),(4,5,6)])
print("multidimensional array:" ,'\n',a)

multidimensional array: 
 [[1 2 3]
 [4 5 6]]


### 1.2 np.zeros(), np.ones(), np.empty()
Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers

several functions to create arrays with initial placeholder content. These minimize the necessity of
growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones,
and the function empty creates an array whose initial content is random and depends on the state
of the memory. By default, the dtype of the created array is float64. 

* np.zeros(shape, dtype=float,order='C')
* np.zeros(shape, dtype=float, order='C')
* np.ones(shape, dtype=None, order='C')
* np.empty(shape, dtype=float, order='C')

In [ ]:
c = np.zeros([2,2]) #([row,col])
print("array full of zeros:",'\n',c)

array full of zeros: 
 [[0. 0.]
 [0. 0.]]


In [ ]:
c = np.zeros((2,2)) #((row,col))
print("array full of zeros:",'\n',c)

array full of zeros: 
 [[0. 0.]
 [0. 0.]]


In [ ]:
d = np.ones([3,3])#([row,col])
print("array full of ones: \n",d)

array full of ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
d = np.ones((2,2))
print("array full of ones: \n",d)

array full of ones: 
 [[1. 1.]
 [1. 1.]]


### 1.3 np.eye()
create identity matrix

Return a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(N, M=None, k=0, dtype=float, order='C')

In [ ]:
print(np.eye(5)) ## square matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 1.4 np.asarray()

Convert the input to an array.

np.asarray(a, dtype = None, order = None)

In [ ]:
e = np.asarray([1,2,3,4,5,6])
print("one-dimensional array: \n", e)

one-dimensional array: 
 [1 2 3 4 5 6]


### 1.5 the difference between array() and asarray()

The main difference is that array (by default) will make a copy of the object, while asarray will not
unless necessary.

In [ ]:
a = np.array([1, 2], dtype=np.float32)

print("data: ",np.array(a, dtype=np.float32) is a)
print("data:",np.array(a, dtype=np.float64) is a)
print("data: ",np.asarray(a, dtype=np.float32) is a)
print("data:",np.asarray(a, dtype=np.float64) is a)


data:  False
data: False
data:  True
data: False


### 1.6 np.arange()
To create sequences of numbers, NumPy provides the arange function which is analogous to the
Python built-in range, but returns an array.

numpy.arange([start, ]stop, [step, ]dtype=None)

 * start: number, optional; Start of interval. The interval includes this value. The default start value is 0.
 * stop: number,End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point         round-off affects the length of out.
 * step: number, optional; Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The         default step size is 1. If step is specified as a position argument, start must also be given.

In [ ]:
f = np.arange(10,100,2)
print("sequences of numbers in array:",f)

sequences of numbers in array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


### 1.7 np.linspace()

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

 * np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [ ]:
h=np.linspace(0,1,20)
h

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
g = np.linspace(0,99,10)
print(g)

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


## 2. Important attributes of an ndarray object

* ndarray.ndim

  the number of axes (dimensions) of the array.
  
* ndarray.shape

    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m     columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
    
* ndarray.size

  the total number of elements of the array. This is equal to the product of the elements of shape.
  
* ndarray.dtype

    an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally         NumPy provides types of its own.
    numpy.int32, numpy.int16, and numpy.float64 are some examples.
    
* ndarray.itemsize

    the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type     complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
    
* ndarray.data

    the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements       in an array using indexing facilities.

In [ ]:
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float32)  #3*2
a.shape

(3, 2)

In [ ]:
a.size

6

In [ ]:
a.ndim

2

In [ ]:
a.dtype

dtype('float32')

## 3. Indexing, Slicing and Iterating

ndrrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = a[0][1]
print('a: \n',a)
print('b:',b)

a: 
 [[1 2]
 [3 4]]
b: 2


In [ ]:
a[0:1,0:2]       #a[first_index :lastindex+1, first_index:last_index+1]

array([[1, 2]])

In [ ]:
l=[[1, 2], [3, 4]]
l[0:1,0:2]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
a[0:1][0:2]

array([[1, 2]])

In [ ]:
# Slicing
a = np.arange(10)

print(a[2:8:2])
print(a[2:8])
print(a[2])
print(a[2:])

[2 4 6]
[2 3 4 5 6 7]
2
[2 3 4 5 6 7 8 9]


## 4. Change the shape of an array

Gives a new shape to an array without changing its data.

* numpy.reshape(a, newshape, order='C')

In [ ]:
a = np.arange(6)

b = a.reshape(2,3) # rows,cols
print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


## 5. Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic
operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array
so that they have compatible shapes. Broadcasting provides a means of vectorizing array
operations so that looping occurs in C instead of Python. It does this without making needless
copies of data and usually leads to efficient algorithm implementations. There are, however, cases
where broadcasting is a bad idea because it leads to inefficient use of memory that slows
computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the
simplest case, the two arrays must have exactly the same shape,

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a * b
print(c)

[ 1  4  9 16]


When operating on two arrays, NumPy compares their shapes element-wise. It starts with the

trailing dimensions and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

If these conditions are not met, a ValueError: operands could not be broadcast together exception
is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the
size that is not 1 along each axis of the inputs.

Arrays do not need to have the same number of dimensions. For example, if you have a
256x256x3 array of RGB values, and you want to scale each color in the image by a different
value, you can multiply the image by a one-dimensional array with 3 values.

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = np.array([1, 2, 3])                              
print(a.shape)  
print(b.shape)
print("b = \n",b)

(3, 3)
(3,)
b = 
 [1 2 3]


In [ ]:
np.array([b,b,b])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
c = a + b
print("a:\n",a)
print("broadcasting:\n",c)

a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasting:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## 6. NumPy common functions

### 6.1 ndarray.flat()

A 1-D iterator over the array.

This is a numpy.flatiter instance, which acts similarly to, but is not a subclass of, Python’s built-in
iterator object.

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a.flat[:])

[1 2 3 4 5 6 7 8 9]


### 6.2 ndarray.transpose()
Returns a view of the array with axes transposed

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a)
print("transpose : ")
print(np.transpose(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 6.3 numpy.concatenate((a1, a2, ...), axis=0, out=None)

Join a sequence of arrays along an existing axis.

 * a1, a2, ...: The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).
 * axis:The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

print("a \n",a)
print("b \n",b)

a 
 [[0 1 2]
 [3 4 5]]
b 
 [[ 7  8  9]
 [10 11 12]]


In [ ]:
print(np.concatenate((a,b), axis = 0)) #axis=0 row
print()
print(np.concatenate((a,b), axis = 1)) #axis=1 col

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [ ]:
print(np.concatenate((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


## 6.7 numpy.delete(arr, obj, axis=None)

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns
those entries not returned by arr[obj].

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.delete(a,1,axis=1)   
c = np.delete(a,1)
print('a= \n',a)
print('b= \n',b)
print('c= \n',c)   

a= 
 [[0 1 2]
 [3 4 5]]
b= 
 [[0 2]
 [3 5]]
c= 
 [0 2 3 4 5]


# 7. Matrix

This module contains all functions in the numpy namespace, with the following replacement functions that return matrices instead of ndarrays.

 * empty(shape[, dtype, order])
 
   Return a new matrix of given shape and type, without initializing entries.
   
 * zeros(shape[, dtype, order])
 
   Return a matrix of given shape and type, filled with zeros.
   
 * ones(shape[, dtype, order])
    Return Matrix of ones.
    
 * eye(n[, M, k, dtype, order])
 
   Return a matrix with ones on the diagonal and zeros elsewhere.
   
 * identity(n[, dtype])
 
   Returns the square identity matrix of given size.
   
 * repmat(a, m, n)
 
   Repeat a 0-D to 2-D array or matrix MxN times.
   
 * rand(*args)
 
   Return a matrix of random values with given shape.
   
 * randn(*args)
 
   Return a random matrix with data from the “standard normal” distribution.

##  7.1 creat a matrix by np.matlib.zeros() and np.matlib.ones()

In [ ]:
from numpy import matlib

In [ ]:
a=matlib.zeros((2,2)) # matrix full of zeros
b=matlib.ones((2,2)) # matrix full of ones
print('a=')
print(a)
print('b=')
print(b)

a=
[[0. 0.]
 [0. 0.]]
b=
[[1. 1.]
 [1. 1.]]


### 7.2 creat a diagonal matrix by np.matlib.eye()

In [ ]:
c=np.matlib.eye(3)
print('c=')
print(c)

c=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 7.3 transfer between array and matrix

In [ ]:
# transfer an array to a matrix
d = np.array([[1,2],[3,4]])
d = np.mat(d)
print(d)
print(type(d))
# transfer a matrix to an array
a=np.mat([[1,2,3],[4,5,6]])
b=a.getA()
print('matrix a=')
print(a)
print(type(a))
print('array b=')
print(b)
print(type(b))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
matrix a=
[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>
array b=
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### 7.4 randomly create a matrix by np.matlib.rand()

In [ ]:
a=np.matlib.rand(3,3)  #0-->1
print('a=',a) 

a= [[0.70945994 0.05755482 0.38317359]
 [0.81396662 0.67205555 0.8817114 ]
 [0.98688524 0.26801778 0.2208896 ]]


### 7.7 matrix operations

matrix.dot(b, out=None) / numpy.dot(a, b, out=None)

Dot product of two arrays.

Dot product of two arrays. Specifically,

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

* If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

* If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

* If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

* If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

  * dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 1], [2, 2]])
print("a")
print(a)
print("b")
print(b)

print(np.dot(a, b)) # matrix multiplication
print(a@b) # matrix multiplication
print(np.matmul(a,b)) 

print(np.multiply(a,b)) #*
print(a*b)

a
[[1 0]
 [0 1]]
b
[[1 1]
 [2 2]]
[[1 1]
 [2 2]]
[[1 1]
 [2 2]]
[[1 1]
 [2 2]]
[[1 0]
 [0 2]]
[[1 0]
 [0 2]]


In [ ]:
print(np.multiply(a,b)) # equivalent to multiply
print(a*b) # equivalent to multiply

[[1 0]
 [0 2]]
[[1 0]
 [0 2]]


## # 7.5 mat/matrix/asmatrix:

Functions that are also in the numpy namespace and return matrices

 * mat(data[, dtype])
  * Interpret the input as a matrix.
 * matrix(data[, dtype, copy])
  * Note: It is no longer recommended to use this class, even for linear
 * asmatrix(data[, dtype])
  * Interpret the input as a matrix.

In [ ]:
a=np.array([1,2,3])
b=np.mat(a)
d=np.asmatrix(a)
c=np.matrix(a)
print('array a=')
print(a)
print('matrix b=')
print(b)
print('matrix c=')
print(c)
print('matrix d=')
print(d)

array a=
[1 2 3]
matrix b=
[[1 2 3]]
matrix c=
[[1 2 3]]
matrix d=
[[1 2 3]]


### 7.8 Matrix Inverse

In [ ]:
a=np.matrix([[2,0,0],
[0,1,0],
[0,0,2]])
b=a.I 
print('matrix a=')
print(a)
print('matrix b=')
print(b)

matrix a=
[[2 0 0]
 [0 1 0]
 [0 0 2]]
matrix b=
[[0.5 0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]


### 7.9 Determinant of a Matrix

In [ ]:
# |A|

a=np.matrix([[1,2],
[3,4]])

b=np.linalg.det(a)
print('matrix a=')
print(a)
print(' b=')
print(b)

matrix a=
[[1 2]
 [3 4]]
 b=
-2.0000000000000004


### 7.10 sum,max,min

In [ ]:
a=np.matrix([[1,2],
[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [ ]:
b=a.sum(axis=0)  #sum by columns
c=a.sum(axis=1)  #sum of raws

print(' b=',b)
print(' c=')
print(c)

 b= [[4 6]]
 c=
[[3]
 [7]]


In [ ]:
d=a.max()
e=a.min()
print(' d=',d)
print(' e=',e)

 d= 4
 e= 1


## 8. Random sampling

### 8.1 Simple random data

 * rand(d0, d1, ..., dn) Random values ([0.0, 1.0)) in a given shape.
 * randn(d0, d1, ..., dn) Return a sample (or samples) from the “standard normal” distribution.
 * randint(low[, high, size, dtype]) Return random integers from low (inclusive) to high (exclusive).

In [ ]:
r1=np.random.rand(2,2)   # return value from 0 => 1
r2=np.random.randn(2,2)  # return vaue from  standard distibution 
r3=np.random.randint(0,5)
print('r1=','\n',r1)
print('r2=','\n',r2)
print('r3=','\n',r3)

r1= 
 [[0.77115699 0.71495052]
 [0.15927913 0.33792276]]
r2= 
 [[ 1.64066188 -0.4482385 ]
 [-0.281003   -1.71800181]]
r3= 
 4


* numpy.random.choice(a, size=None, replace=True, p=None)
  * a : If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if a was np.arange(n)
  
  * size : Output shape.
  
  * replace : boolean, optional; Whether the sample is with or without replacement
  
  * p : 1-D array-like, optional; The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution         over all entries in a.

In [ ]:
r3=np.random.choice([1,2,3,4,5], (2,2), p=[0.2, 0.2, 0.2, 0.2, 0.2])
print(r3)

[[4 3]
 [5 2]]


In [ ]:
a=np.array([1,2,3,4,5])
print('a=','\n',a)
np.random.shuffle(a) # rearange a given sequance
print('a=','\n',a)
c=np.random.permutation(a)# return copy of a given sequence
print('a=','\n',a)
print('c=','\n',c)

a= 
 [1 2 3 4 5]
a= 
 [3 4 2 1 5]
a= 
 [3 4 2 1 5]
c= 
 [1 3 5 4 2]


### 8.3 Distributions

* normal([loc, scale, size]) Draw random samples from a normal (Gaussian) distribution.

  * loc : Mean (“centre”) of the distribution.
  
  * scale : Standard deviation (spread or “width”) of the distribution.
  
  * size : Output shape.
  
  
* uniform([low, high, size]) Draw samples from a uniform distribution.

  * Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). In other words, any value          within the given interval is equally likely to be drawn by uniform.
  
  * low : Lower boundary of the output interval. All values generated will be greater than or equal to low. The default value is 0.
  
  * high : Upper boundary of the output interval. All values generated will be less than high. The default value is 1.0.
  
  * size : Output shape.
  
  * poisson([lam, size]) Draw samples from a Poisson distribution.
  
  * lam : Expectation of interval, should be >= 0. A sequence of expectation intervals must be broadcastable over the requested size.
  
  * size : Output shape.

In [ ]:
r1=np.random.normal(0,0.1,5)  # mean , sandard devietion , size
r2=np.random.uniform(0,5,2)   # 0-> 5 
r3=np.random.poisson(5,2)   # exceptation of interval , shape
print('r1=','\n',r1)
print('r2=','\n',r2)

print('r3=','\n',r3)

r1= 
 [ 0.07250858  0.01487667  0.11534487 -0.0513803   0.01649688]
r2= 
 [1.13803444 4.50925392]
r3= 
 [3 4]


## 9. Common mathematical functions

### 9.1 Trigonometric functions

 * sin(x, /[, out, where, casting, order, ...]) Trigonometric sine, element-wise.
 * cos(x, /[, out, where, casting, order, ...]) Cosine element-wise

In [ ]:
a=np.array([0,30,45,60,90])
b=np.sin(a*np.pi/180)
c=np.cos(a*np.pi/180)
print('b=','\n',b)
print('c=','\n',c)

b= 
 [0.         0.5        0.70710678 0.8660254  1.        ]
c= 
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


### 9.2 Rounding

 * around(a[, decimals, out]) Evenly round to the given number of decimals.
 * floor(x, /[, out, where, casting, order, ...]) Return the floor of the input, element-wise.
 * ceil(x, /[, out, where, casting, order, ...]) Return the ceiling of the input, element-wise.

In [ ]:
a=np.array([1.7111,1.555,2.748,2.55])
b=np.around(a)
c=np.around(a,decimals=1) # one digit after decimal point
print('b=',b)
print('c=',c)

b= [2. 2. 3. 3.]
c= [1.7 1.6 2.7 2.6]


In [ ]:
d=np.floor(a)
e=np.ceil(a)
print('d=',d)
print('e=',e)

d= [1. 1. 2. 2.]
e= [2. 2. 3. 3.]


### 9.3 Arithmetic operations

In [ ]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
c=np.add(a,b)
d=np.subtract(a,b)
e=np.multiply(a,b)
f=np.divide(a,b)
g=np.mod(a,b)
h=np.power(a,b)
print('c=',c)
print('d=',d)
print('e=',e)
print('f=',f)
print('g=',g)
print('h=',h)

c= [5 5 5 5]
d= [-3 -1  1  3]
e= [4 6 6 4]
f= [0.25       0.66666667 1.5        4.        ]
g= [1 2 1 0]
h= [1 8 9 4]


### 9.5 Sort function

 * numpy.sort(a, axis=-1, kind='quicksort', order=None)
 
Return a sorted copy of an array.


In [ ]:
a=np.array([[3,5,1],[2,8,7]])
print(a)
b=np.sort(a)
print(b)


[[3 5 1]
 [2 8 7]]
[[1 3 5]
 [2 7 8]]
